defaults: &defaults
  working_directory: ~/gopher-boy
  docker:
    - image: bokuweb/node-go-with-browser:latest
      environment:
        TZ: Asia/Tokyo
        GOPATH: /home/circleci/go
version: 2
jobs:
  build:
    <<: *defaults
    steps:
  